# Generated by Django 3.2.12 on 2022-05-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ara_ako', '0002_auto_20220406_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='araakoevent',
            options={'ordering': ['-event__start_datetime']},
        ),
    ]
