# Generated by Django 2.2.18 on 2021-04-20 00:30

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0009_auto_20200309_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name')),
                ('published', models.BooleanField(default=False)),
                ('visibility', models.PositiveSmallIntegerField(choices=[(1, 'Hidden'), (2, 'Coming soon'), (3, 'Published')], default=1)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_started_component', to='resources.Resource', verbose_name='resource')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
