# Generated by Django 2.2.18 on 2021-04-20 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_started', '0002_auto_20210420_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='resource',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_started_component', to='resources.Resource', verbose_name='resource'),
        ),
    ]
