# Generated by Django 3.2.12 on 2022-04-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_started', '0003_auto_20210420_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
