# Generated by Django 2.1.5 on 2019-03-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('curriculum_area', models.CharField(max_length=100)),
                ('curriculum_area_code', models.CharField(max_length=10)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('component', models.CharField(max_length=100)),
                ('component_code', models.CharField(max_length=10)),
                ('strand', models.CharField(max_length=100)),
                ('strand_code', models.CharField(max_length=10)),
                ('content', models.TextField()),
            ],
        ),
    ]
