# Generated by Django 2.1.5 on 2019-03-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentic_context_cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementobjective',
            old_name='curriculum_area',
            new_name='learning_area',
        ),
        migrations.RenameField(
            model_name='achievementobjective',
            old_name='curriculum_area_code',
            new_name='learning_area_code',
        ),
    ]
