# Generated by Django 2.1.5 on 2019-06-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic_context_cards', '0002_auto_20190320_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_outcome_number', models.PositiveSmallIntegerField(default=1)),
                ('code', models.CharField(max_length=30)),
                ('learning_area', models.CharField(max_length=100)),
                ('learning_area_code', models.CharField(max_length=10)),
                ('technological_area', models.CharField(max_length=100)),
                ('technological_area_code', models.CharField(max_length=10)),
                ('content', models.TextField()),
            ],
        ),
    ]
