version: '3.8'

# --- Base config -------------------------------------------------------------

x-default-opts:
    &default-opts
    logging:
        options:
            max-size: '1m'
            max-file: '3'

# --- Base Django config ------------------------------------------------------

x-django-config:
    &django-config
    image: ghcr.io/uccser/dthm4kaiako:${DTHM4KAIAKO_IMAGE_TAG}
    environment:
        dthm4kaiako_DOMAIN: ${DTHM4KAIAKO_DOMAIN}
        POSTGRES_HOST: postgres
        POSTGRES_PORT: "5432"
        DEPLOYMENT_ENVIRONMENT_FILE: /dthm4kaiako_deployment_environment
        DJANGO_SECRET_KEY_FILE: /run/secrets/dthm4kaiako_django_secret_key
        POSTGRES_DB_FILE: /run/secrets/dthm4kaiako_postgres_db
        POSTGRES_USER_FILE: /run/secrets/dthm4kaiako_postgres_user
        POSTGRES_PASSWORD_FILE: /run/secrets/dthm4kaiako_postgres_password
        MAILGUN_API_KEY_FILE: /run/secrets/dthm4kaiako_mailgun_api_key
        GOOGLE_DRIVE_API_KEY_FILE: /run/secrets/dthm4kaiako_google_drive_api_key
        GOOGLE_MAPS_API_KEY_FILE: /run/secrets/dthm4kaiako_google_maps_api_key
        GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/dthm4kaiako_google_service_account
        GOOGLE_CLOUD_STORAGE_BUCKET_MEDIA_NAME_FILE: /run/secrets/dthm4kaiako_google_cloud_storage_bucket_media_name
        SAMPLE_DATA_ADMIN_PASSWORD_FILE: /run/secrets/dthm4kaiako_sample_data_admin_password
        SAMPLE_DATA_USER_PASSWORD_FILE: /run/secrets/dthm4kaiako_sample_data_user_password
        RECAPTCHA_PUBLIC_KEY_FILE: /run/secrets/dthm4kaiako_recaptcha_public_key
        RECAPTCHA_PRIVATE_KEY_FILE: /run/secrets/dthm4kaiako_recaptcha_private_key
    configs:
        - dthm4kaiako_deployment_environment
    secrets:
        - dthm4kaiako_django_secret_key
        - dthm4kaiako_postgres_db
        - dthm4kaiako_postgres_user
        - dthm4kaiako_postgres_password
        - dthm4kaiako_mailgun_api_key
        - dthm4kaiako_google_drive_api_key
        - dthm4kaiako_google_maps_api_key
        - dthm4kaiako_google_service_account
        - dthm4kaiako_google_cloud_storage_bucket_media_name
        - dthm4kaiako_sample_data_admin_password
        - dthm4kaiako_sample_data_user_password
        - dthm4kaiako_recaptcha_public_key
        - dthm4kaiako_recaptcha_private_key

# -----------------------------------------------------------------------------

services:
    django:
        <<: *default-opts
        <<: *django-config
        deploy:
            replicas: 2
            placement:
                constraints:
                    - node.role==worker
                    - node.labels.role==apps
            restart_policy:
                condition: on-failure
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=uccser-public"
                - "traefik.http.services.dthm4kaiako-django.loadbalancer.server.port=8000"
                - "traefik.http.routers.dthm4kaiako-django.service=dthm4kaiako-django"
                - "traefik.http.routers.dthm4kaiako-django.rule=${DTHM4KAIAKO_ROUTER_RULE}"
                - "traefik.http.routers.dthm4kaiako-django.entryPoints=web"
                # Redirect non-www to www, only triggers in production swarm.
                - "traefik.http.middlewares.dthm4kaiako-redirect-non-www.redirectregex.regex=^https://dthm4kaiako(.*)"
                - "traefik.http.middlewares.dthm4kaiako-redirect-non-www.redirectregex.replacement=https://www.dthm4kaiako$${1}"
                - "traefik.http.middlewares.dthm4kaiako-redirect-non-www.redirectregex.permanent=true"
        networks:
            - uccser-public
            - backend

    task-update-data:
        <<: *default-opts
        <<: *django-config
        command: python ./manage.py update_data
        deploy:
            replicas: 0
            placement:
                constraints:
                    - node.role==worker
                    - node.labels.role==apps
            restart_policy:
                condition: none
        networks:
            - backend

    postgres:
        <<: *default-opts
        image: postgis/postgis:13-3.2
        # TODO: Write test script that reads secret files
        # to get correct username
        # healthcheck:
        #     test: ["CMD-SHELL", "pg_isready -U postgres"]
        #     start_period: 10s
        #     interval: 10s
        #     timeout: 5s
        #     retries: 3
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role==worker
                    - node.labels.role==data
            restart_policy:
                condition: on-failure
        environment:
            POSTGRES_DB_FILE: /run/secrets/dthm4kaiako_postgres_db
            POSTGRES_USER_FILE: /run/secrets/dthm4kaiako_postgres_user
            POSTGRES_PASSWORD_FILE: /run/secrets/dthm4kaiako_postgres_password
        secrets:
            - dthm4kaiako_postgres_db
            - dthm4kaiako_postgres_user
            - dthm4kaiako_postgres_password
        networks:
            - backend
        volumes:
            - postgres-data:/var/lib/postgresql/data:z
            - postgres-data-backups:/backups:z

configs:
    dthm4kaiako_deployment_environment:
        external: true

secrets:
    dthm4kaiako_django_secret_key:
        external: true
    dthm4kaiako_postgres_db:
        external: true
    dthm4kaiako_postgres_user:
        external: true
    dthm4kaiako_postgres_password:
        external: true
    dthm4kaiako_mailgun_api_key:
        external: true
    dthm4kaiako_google_drive_api_key:
        external: true
    dthm4kaiako_google_maps_api_key:
        external: true
    dthm4kaiako_google_service_account:
        external: true
    dthm4kaiako_google_cloud_storage_bucket_media_name:
        external: true
    dthm4kaiako_sample_data_admin_password:
        external: true
    dthm4kaiako_sample_data_user_password:
        external: true
    dthm4kaiako_recaptcha_public_key:
        external: true
    dthm4kaiako_recaptcha_private_key:
        external: true

networks:
    uccser-public:
        external: true
    backend:
        driver: overlay
        attachable: true

volumes:
    postgres-data: {}
    postgres-data-backups: {}
