# This Dockerfile is based off the Google App Engine Python runtime image
# https://github.com/GoogleCloudPlatform/python-runtime
FROM ghcr.io/uccser/django-with-weasyprint:2.2.18

RUN apt-get update \
    && apt-get install -y \
        binutils \
        libproj-dev \
        gdal-bin

ENV DJANGO_PRODUCTION=False

# Copy and install dependencies inside virtual environment
COPY requirements /requirements
RUN /docker_venv/bin/pip3 install -r /requirements/local.txt

RUN mkdir /dthm4kaiako/
WORKDIR /dthm4kaiako/

# Copy and install fonts
COPY dthm4kaiako/static/fonts/ /usr/share/fonts/
RUN fc-cache -fv
