FROM ghcr.io/uccser/django:2.2.18-with-weasyprint

RUN apt-get update \
    && apt-get install -y \
        binutils \
        libproj-dev \
        gdal-bin

ENV DJANGO_PRODUCTION=False

# Copy and install dependencies inside virtual environment
COPY requirements /requirements
RUN /docker_venv/bin/pip3 install -r /requirements/local.txt

RUN mkdir -p /dthm4kaiako/dthm4kaiako/
WORKDIR /dthm4kaiako/dthm4kaiako/

# Copy and install fonts
COPY dthm4kaiako/static/fonts/ /usr/share/fonts/
RUN fc-cache -fv
