# Generated by Django 2.1.5 on 2019-07-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressOutcomeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('progress_outcomes', models.ManyToManyField(blank=True, related_name='groups', to='poet.ProgressOutcome')),
            ],
        ),
    ]
