# Generated by Django 2.1.5 on 2019-07-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0002_progressoutcomegroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressoutcomegroup',
            options={'ordering': ['name']},
        ),
    ]
