# Generated by Django 2.1.5 on 2019-08-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0005_auto_20190801_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
