# Generated by Django 2.1.5 on 2019-01-21 02:25

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
