# Generated by Django 2.1.5 on 2019-01-23 20:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
