# Generated by Django 2.1.5 on 2019-01-23 20:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0002_auto_20190124_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
