# Generated by Django 2.1.5 on 2019-01-24 00:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0003_auto_20190124_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
