# Generated by Django 2.1.5 on 2019-01-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
