# Generated by Django 2.1.5 on 2019-01-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0006_relatedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedlink',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
