# Generated by Django 2.1.5 on 2019-02-02 08:10

from django.db import migrations, models
import utils.get_upload_filepath


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0009_auto_20190202_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticleaudience',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='newsarticleaudience',
            name='colour',
            field=models.CharField(help_text="Available colours: 'red', 'pink', 'orange', 'yellow', 'green', 'teal', 'cyan', 'blue', 'indigo', 'purple', 'gray', 'gray-dark'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='newsarticlesource',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo will be displayed instead of name if provided.', null=True, upload_to=utils.get_upload_filepath.get_dtta_news_article_source_upload_path),
        ),
    ]
