# Generated by Django 2.1.5 on 2019-02-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0010_auto_20190202_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticleaudience',
            name='colour',
            field=models.CharField(help_text="Available colours: 'red', 'pink', 'orange', 'yellow', 'green','teal', 'cyan', 'blue', 'indigo', 'purple', 'gray', 'gray-dark'.", max_length=20),
        ),
    ]
