# Generated by Django 3.2.12 on 2022-05-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtta', '0014_page_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Planning'), (2, 'Documents'), (3, 'About'), (4, 'Membership')], default=1),
        ),
    ]
