# Generated by Django 2.1.5 on 2019-09-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('template', models.CharField(help_text='File extension (.html) is not required.', max_length=300)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
