# Generated by Django 2.1.5 on 2019-01-26 08:47

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.get_upload_filepath


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True)),
                ('file_obj', models.FileField(blank=True, null=True, upload_to=utils.get_upload_filepath.get_resource_upload_path)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.get_upload_filepath.get_resource_upload_path)),
                ('component_type', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (10, 'Document'), (20, 'Image'), (30, 'Slideshow'), (40, 'Video'), (50, 'Website')], default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='resources.Resource')),
            ],
        ),
    ]
