# Generated by Django 2.1.5 on 2019-01-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='published',
        ),
    ]
