# Generated by Django 2.1.5 on 2019-01-28 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcecomponent',
            old_name='file_obj',
            new_name='component_file',
        ),
        migrations.RenameField(
            model_name='resourcecomponent',
            old_name='image',
            new_name='component_image',
        ),
        migrations.RenameField(
            model_name='resourcecomponent',
            old_name='url',
            new_name='component_url',
        ),
        migrations.AddField(
            model_name='resourcecomponent',
            name='component_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_of', to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='resourcecomponent',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcecomponent',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
