# Generated by Django 2.1.5 on 2019-01-25 10:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name'),
        ),
    ]
