# Generated by Django 2.1.5 on 2019-02-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20190203_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecomponent',
            name='component_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (10, 'Document'), (11, 'PDF'), (90, 'Spreadsheet'), (20, 'Image'), (30, 'Slideshow'), (40, 'Video'), (50, 'Website'), (60, 'Audio'), (70, 'Archive'), (80, 'Resource')], default=0),
        ),
    ]
