# Generated by Django 2.1.5 on 2019-02-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20190203_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumLearningArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('css_class', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('css_class', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NZQAStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'NCEA Level 1'), (2, 'NCEA Level 2'), (3, 'NCEA Level 3')], default=1)),
            ],
            options={
                'verbose_name': 'NZQA standard',
                'ordering': ['level', 'abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='ProgressOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('abbreviation', models.CharField(max_length=10)),
                ('css_class', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyCurriculumStrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('abbreviation', models.CharField(max_length=10)),
                ('css_class', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.AlterField(
            model_name='resourcecomponent',
            name='component_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (10, 'Document'), (11, 'PDF'), (90, 'Spreadsheet'), (20, 'Image'), (30, 'Slideshow'), (40, 'Video'), (50, 'Website'), (60, 'Audio'), (70, 'Archive'), (80, 'Resource')], default=0),
        ),
        migrations.AddField(
            model_name='progressoutcome',
            name='technology_curriculum_strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_outcomes', to='resources.TechnologyCurriculumStrand'),
        ),
        migrations.AddField(
            model_name='resource',
            name='curriculum_learning_areas',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.CurriculumLearningArea'),
        ),
        migrations.AddField(
            model_name='resource',
            name='languages',
            field=models.ManyToManyField(related_name='resources', to='resources.Language'),
        ),
        migrations.AddField(
            model_name='resource',
            name='nzqa_standards',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.NZQAStandard'),
        ),
        migrations.AddField(
            model_name='resource',
            name='progress_outcomes',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.ProgressOutcome'),
        ),
        migrations.AddField(
            model_name='resource',
            name='technology_curriculum_strands',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.TechnologyCurriculumStrand'),
        ),
        migrations.AddField(
            model_name='resource',
            name='year_levels',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.YearLevel'),
        ),
    ]
