# Generated by Django 2.1.5 on 2019-02-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20190214_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumLearningArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('css_class', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumStrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('abbreviation', models.CharField(max_length=10)),
                ('css_class', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('css_class', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NZQAStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=20)),
                ('css_class', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('abbreviation', models.CharField(max_length=10)),
                ('css_class', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='curriculum_learning_areas',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.CurriculumLearningArea'),
        ),
        migrations.AddField(
            model_name='resource',
            name='curriculum_strands',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.CurriculumStrand'),
        ),
        migrations.AddField(
            model_name='resource',
            name='languages',
            field=models.ManyToManyField(related_name='resources', to='resources.Language'),
        ),
        migrations.AddField(
            model_name='resource',
            name='nzqa_standards',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.NZQAStandard'),
        ),
        migrations.AddField(
            model_name='resource',
            name='progress_outcomes',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.ProgressOutcome'),
        ),
        migrations.AddField(
            model_name='resource',
            name='year_levels',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.YearLevel'),
        ),
    ]
