# Generated by Django 2.1.5 on 2019-02-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20190215_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nzqastandard',
            options={'verbose_name': 'NZQA standard'},
        ),
        migrations.AlterField(
            model_name='curriculumlearningarea',
            name='css_class',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='curriculumstrand',
            name='css_class',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='language',
            name='css_class',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='nzqastandard',
            name='css_class',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='progressoutcome',
            name='css_class',
            field=models.CharField(max_length=30),
        ),
    ]
