# Generated by Django 2.1.5 on 2019-02-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20190219_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnologyCurriculumStrand',
            new_name='TechnologicalArea',
        ),
        migrations.RenameField(
            model_name='progressoutcome',
            old_name='technology_curriculum_strand',
            new_name='technological_area',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='technology_curriculum_strands',
            new_name='technological_areas',
        ),
    ]
