# Generated by Django 2.1.5 on 2019-02-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20190215_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurriculumStrand',
            new_name='TechnologyCurriculumStrand',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='curriculum_strands',
            new_name='technology_curriculum_strands',
        ),
    ]
