# Generated by Django 2.1.5 on 2019-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20190222_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='nzqastandard',
            name='credit_value',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nzqastandard',
            name='standard_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Internal'), (2, 'External')], default=1),
        ),
    ]
