# Generated by Django 2.1.5 on 2019-02-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20190216_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlevel',
            options={'ordering': ['level']},
        ),
    ]
