# Generated by Django 2.1.5 on 2019-02-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20190217_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumlearningarea',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='nzqastandard',
            options={'ordering': ['abbreviation'], 'verbose_name': 'NZQA standard'},
        ),
        migrations.AlterModelOptions(
            name='progressoutcome',
            options={'ordering': ['abbreviation']},
        ),
        migrations.AlterModelOptions(
            name='technologycurriculumstrand',
            options={'ordering': ['abbreviation']},
        ),
    ]
