# Generated by Django 2.1.5 on 2019-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20190217_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nzqastandard',
            name='css_class',
        ),
        migrations.AddField(
            model_name='nzqastandard',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NCEA Level 1'), (2, 'NCEA Level 2'), (3, 'NCEA Level 3')], default=1),
        ),
    ]
