# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='published',
            new_name='is_published',
        ),
    ]
