# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170618_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(null=True)),
                ('sessions', models.ManyToManyField(related_name='resources', to='events.Session')),
            ],
        ),
        migrations.RenameField(
            model_name='location',
            old_name='event',
            new_name='sessions',
        ),
    ]
