# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170618_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='sessions',
        ),
        migrations.AddField(
            model_name='session',
            name='locations',
            field=models.ManyToManyField(related_name='sessions', to='events.Location'),
        ),
        migrations.AddField(
            model_name='session',
            name='resources',
            field=models.ManyToManyField(related_name='sessions', to='events.Resource'),
        ),
    ]
