# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170618_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='events.Resource'),
        ),
    ]
