# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170618_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_datetime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
