# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20170621_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('locations', models.ManyToManyField(blank=True, related_name='third_party_events', to='events.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
