# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_thirdpartyevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyevent',
            name='end_datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='thirdpartyevent',
            name='start_datetime',
            field=models.DateField(),
        ),
    ]
