# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20170624_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdpartyevent',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='thirdpartyevent',
            old_name='start_datetime',
            new_name='start_date',
        ),
    ]
