# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20170624_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartyevent',
            name='locations',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(null=True, related_name='events', to='events.Sponsor'),
        ),
        migrations.AddField(
            model_name='thirdpartyevent',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_party_events', to='events.Location'),
        ),
    ]
