# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20170705_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(related_name='events', to='events.Sponsor'),
        ),
    ]
