# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20170709_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Sponsor'),
        ),
    ]
