# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20170715_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
