# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 15:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20170716_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=events.models.EventBase.create_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='thirdpartyevent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=events.models.EventBase.create_slug, unique=True),
        ),
    ]
