# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20170716_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='location',
            new_name='event',
        ),
    ]
