# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20170716_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
