# Generated by Django 2.1.5 on 2020-03-06 01:34

from django.db import migrations, models
import utils.get_upload_filepath


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190215_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo will be displayed instead of name if provided.', null=True, upload_to=utils.get_upload_filepath.get_entity_upload_path)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
