# Generated by Django 2.1.5 on 2021-01-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200307_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.TextField(default='', verbose_name='billing address'),
        ),
        migrations.AddField(
            model_name='user',
            name='cell_phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='cell phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=150, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_notes',
            field=models.TextField(default='', verbose_name='medical notes'),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.CharField(default='', max_length=350, verbose_name='workplace'),
        ),
    ]
