# Generated by Django 2.1.5 on 2021-01-20 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20210121_0823'),
        ('users', '0007_auto_20210121_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event_applications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='events.EventApplication'),
        ),
    ]
