# Generated by Django 3.2.12 on 2022-04-19 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220406_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'dietary requirements',
                'ordering': ['name'],
            },
        ),
    ]
