# Generated by Django 3.2.12 on 2022-04-20 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_dietaryrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrequirement',
            name='users',
            field=models.ManyToManyField(related_name='dietary_requirement', to=settings.AUTH_USER_MODEL),
        ),
    ]
