# Generated by Django 2.1.5 on 2021-02-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_event_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='event_applications',
        ),
    ]
