# Generated by Django 2.1.5 on 2021-02-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_event_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_requirements',
            field=models.ManyToManyField(blank=True, related_name='dietary_requirements', to='users.DietaryRequirement'),
        ),
    ]
