# Generated by Django 3.2.12 on 2022-05-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_dietaryrequirement_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryrequirement',
            name='show_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dietaryrequirement',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
