# Generated by Django 3.2.12 on 2022-05-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220502_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryrequirement',
            name='show_to_all',
        ),
        migrations.AlterField(
            model_name='dietaryrequirement',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
