# Generated by Django 2.1.5 on 2021-02-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210212_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medical_notes',
            field=models.TextField(blank=True, default='', verbose_name='medical notes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workplace',
            field=models.CharField(blank=True, default='', max_length=350, verbose_name='workplace'),
        ),
    ]
