# Generated by Django 3.2.12 on 2022-05-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220502_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrequirement',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
