# Generated by Django 3.2.12 on 2022-05-07 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_dietaryrequirement_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrequirement',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='dietary_requirement', to=settings.AUTH_USER_MODEL),
        ),
    ]
