# Generated by Django 3.2.13 on 2022-05-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_dietaryrequirement_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryrequirement',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_requirements',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.DietaryRequirement'),
        ),
    ]
