# Generated by Django 3.2.13 on 2022-05-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220521_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.CharField(default='', max_length=1000, verbose_name='billing address'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=150, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.CharField(default='', max_length=200, verbose_name='workplace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dietary_requirements',
            field=models.ManyToManyField(blank=True, default='None', related_name='users', to='users.DietaryRequirement'),
        ),
    ]
