# Generated by Django 3.2.13 on 2022-05-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220523_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cell_phone_number',
            field=models.CharField(default='', max_length=30, verbose_name='cell phone number'),
        ),
    ]
