# Generated by Django 3.2.13 on 2022-05-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_cell_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='workplace',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_address',
        ),
    ]
