# Generated by Django 3.2.13 on 2022-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220528_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cell_phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_phone_number',
            field=models.CharField(default='', max_length=30, verbose_name='mobile phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='', help_text='City your school is located in', max_length=150, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_notes',
            field=models.TextField(default='', help_text='Is there anything we can help you with? e.g. accessibility'),
        ),
    ]
