# Generated by Django 3.2.13 on 2022-05-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220528_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=200, verbose_name='school'),
        ),
    ]
