# Generated by Django 3.2.13 on 2022-05-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medical_notes',
            field=models.TextField(blank=True, default='', help_text='Is there anything we can help you with? e.g. accessibility'),
        ),
    ]
