# Generated by Django 3.2.13 on 2022-07-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_username'),
        ('users', '0021_alter_user_medical_notes'),
    ]

    operations = [
    ]
