# Generated by Django 3.2.14 on 2022-07-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_merge_20220709_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrequirement',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
