# Generated by Django 3.2.14 on 2022-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_dietaryrequirement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrequirement',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
