# Generated by Django 3.2.14 on 2022-07-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_dietaryrequirement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='user',
            name='educational_entities',
            field=models.ManyToManyField(default='', max_length=200, related_name='users', to='users.Entity', verbose_name='What school(s) and/or educational organisation or association are you from?'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Northland region'), (2, 'Auckland region'), (3, 'Waikato region'), (4, 'Bay of Plenty region'), (5, 'Gisborne region'), (6, "Hawke's Bay region"), (7, 'Taranaki region'), (8, 'Manawatu-Wanganui region'), (9, 'Wellington region'), (10, 'Tasman region'), (11, 'Nelson region'), (12, 'Marlborough region'), (13, 'West Coast region'), (14, 'Canterbury region'), (15, 'Otago region'), (16, 'Southland region'), (17, 'Chatman Islands')], default=14, help_text='Region that your school, organisation or association is located in'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_notes',
            field=models.TextField(blank=True, default='', help_text='How can we better look after you? e.g. accessibility, allergies'),
        ),
    ]
