# Generated by Django 3.2.15 on 2022-09-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220905_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_region',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Northland region'), (2, 'Auckland region'), (3, 'Waikato region'), (4, 'Bay of Plenty region'), (5, 'Gisborne region'), (6, "Hawke's Bay region"), (7, 'Taranaki region'), (8, 'Manawatu-Wanganui region'), (9, 'Wellington region'), (10, 'Tasman region'), (11, 'Nelson region'), (12, 'Marlborough region'), (13, 'West Coast region'), (14, 'Canterbury region'), (15, 'Otago region'), (16, 'Southland region'), (17, 'Chatman Islands')], default=14, help_text='Region that your school, organisation or association is located in'),
        ),
    ]
