# Generated by Django 2.1.5 on 2019-03-05 07:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190305_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
