# Generated by Django 2.1.5 on 2019-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190305_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='suburb',
            field=models.CharField(blank=True, help_text='Suburb, for example: Riccarton', max_length=200),
        ),
    ]
