# Generated by Django 2.1.5 on 2019-03-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accessible_online',
            field=models.BooleanField(default=False, help_text='Can this event be attended online'),
        ),
    ]
