# Generated by Django 2.1.5 on 2019-03-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_accessible_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='accessible_online',
            field=models.BooleanField(default=False, help_text='Select if this event be attended online'),
        ),
    ]
