# Generated by Django 2.1.5 on 2019-03-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190306_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start', 'end']},
        ),
    ]
