# Generated by Django 2.1.5 on 2020-02-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200219_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Register to attend event'), (2, 'Apply to attend event'), (3, 'Visit event website')], default=1),
        ),
    ]
