# Generated by Django 2.1.5 on 2020-02-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_registration_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start', 'end', 'name']},
        ),
    ]
