# Generated by Django 2.1.5 on 2021-01-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_migrate_organisers_to_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_submitted', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('C', 'Cancelled'), ('D', 'Declined')], default='P', max_length=1)),
                ('staff_comments', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EventVoucher',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('new_cost', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_open', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('terms_and_conditions', models.TextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationFormSessionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('sessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_choices', to='events.Session')),
            ],
        ),
        migrations.AddField(
            model_name='registrationform',
            name='session_choices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registraion_form', to='events.RegistrationFormSessionChoice'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.EventVoucher'),
        ),
        migrations.AddField(
            model_name='applicanttype',
            name='applications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_type', to='events.EventApplication'),
        ),
        migrations.AddField(
            model_name='event',
            name='applicant_types',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.ApplicantType'),
        ),
        migrations.AddField(
            model_name='event',
            name='applications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.EventApplication'),
        ),
    ]
