# Generated by Django 2.1.5 on 2021-01-21 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20210121_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='session_choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registraion_form', to='events.RegistrationFormSessionChoice'),
        ),
    ]
