# Generated by Django 2.1.5 on 2021-01-26 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20210121_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('C', 'Cancelled'), ('D', 'Declined')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_form', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='session_choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_form', to='events.RegistrationFormSessionChoice'),
        ),
    ]
