# Generated by Django 3.2.12 on 2022-05-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_rename_open_registrationform_available_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime', 'end_datetime']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_datetime', 'end_datetime', 'name']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='start_datetime',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='end',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='start',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='end',
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='userEditable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='end_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='open_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
