# Generated by Django 2.1.5 on 2021-01-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20210127_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventVoucher'),
        ),
    ]
