# Generated by Django 3.2.12 on 2022-05-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20220502_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationform',
            old_name='open',
            new_name='start',
        ),
    ]
