# Generated by Django 3.2.12 on 2022-05-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_rename_open_registrationform_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='event',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registration_form', serialize=False, to='events.event'),
        ),
    ]
