# Generated by Django 2.1.5 on 2021-01-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20210127_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='applicant_types',
        ),
        migrations.AddField(
            model_name='event',
            name='applicant_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.ApplicantType'),
        ),
    ]
