# Generated by Django 2.1.5 on 2021-01-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20210127_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanttype',
            name='applications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_type', to='events.EventApplication'),
        ),
    ]
