# Generated by Django 3.2.12 on 2022-05-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_registrationform_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='userEditable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registration_form', serialize=False, to='events.event'),
        ),
    ]
