# Generated by Django 2.1.5 on 2021-01-27 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20210127_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='applications',
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.Event'),
        ),
    ]
