# Generated by Django 3.2.12 on 2022-05-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_event_registration_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='end',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='start',
        ),
        migrations.AddField(
            model_name='registrationform',
            name='close_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='open_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
