# Generated by Django 3.2.13 on 2022-05-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20220507_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='staff_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
    ]
