# Generated by Django 2.1.5 on 2021-02-16 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_eventapplication_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='applicant_types',
        ),
        migrations.AddField(
            model_name='applicanttype',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_types', to='events.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='applicanttype',
            unique_together={('name', 'event')},
        ),
    ]
