# Generated by Django 3.2.13 on 2022-05-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20220521_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='application_type',
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='applicant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.applicanttype'),
        ),
    ]
