# Generated by Django 3.2.13 on 2022-05-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20220522_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
