# Generated by Django 2.1.5 on 2021-02-17 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20210216_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicanttype',
            name='applications',
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='applicant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.ApplicantType'),
        ),
    ]
