# Generated by Django 3.2.13 on 2022-05-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_alter_eventapplication_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='userEditable',
        ),
    ]
