# Generated by Django 2.1.5 on 2021-02-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20210217_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvoucher',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
