# Generated by Django 2.1.5 on 2021-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_eventvoucher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvoucher',
            name='new_cost',
        ),
        migrations.AddField(
            model_name='eventvoucher',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
