# Generated by Django 3.2.13 on 2022-05-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_alter_eventapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(help_text="Street address' number, for example: 12", max_length=10)),
                ('street_name', models.CharField(help_text="Street address' name, for example: High Street", max_length=200)),
                ('suburb', models.CharField(help_text='Suburb, for example: Riccarton', max_length=200)),
                ('city', models.CharField(default='Christchurch', help_text='Town or city, for example: Christchurch', max_length=200)),
                ('region', models.PositiveSmallIntegerField(choices=[(1, 'Northland region'), (2, 'Auckland region'), (3, 'Waikato region'), (4, 'Bay of Plenty region'), (5, 'Gisborne region'), (6, "Hawke's Bay region"), (7, 'Taranaki region'), (8, 'Manawatu-Wanganui region'), (9, 'Wellington region'), (10, 'Tasman region'), (11, 'Nelson region'), (12, 'Marlborough region'), (13, 'West Coast region'), (14, 'Canterbury region'), (15, 'Otago region'), (16, 'Southland region'), (17, 'Chatman Islands')], default=14)),
                ('post_code', models.IntegerField(default='8041', help_text='Post code, for example: 8041', max_length=4)),
                ('country', models.CharField(default='New Zealand', help_text='Country, for example: New Zealand', max_length=300)),
            ],
        ),
    ]
