# Generated by Django 3.2.13 on 2022-05-28 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.IntegerField(default='8041', help_text='Post code, for example: 8041', validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)]),
        ),
    ]
