# Generated by Django 2.1.5 on 2021-02-25 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_eventvoucher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvoucher',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
