# Generated by Django 3.2.13 on 2022-05-28 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0036_alter_address_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_application', to='events.address'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='applicant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to='events.applicanttype'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_application', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
