# Generated by Django 3.2.13 on 2022-05-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20220528_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_application', to='events.address', verbose_name='billing address'),
        ),
    ]
