# Generated by Django 3.2.13 on 2022-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_eventapplication_billing_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='New Zealand', max_length=300),
        ),
    ]
