# Generated by Django 3.2.13 on 2022-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='billing_email_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
