# Generated by Django 3.2.13 on 2022-05-30 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0042_alter_eventapplication_billing_email_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventapplication',
            unique_together={('event', 'user')},
        ),
    ]
