# Generated by Django 3.2.13 on 2022-05-31 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_alter_eventapplication_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='billing_physical_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_application', to='events.address', verbose_name='billing address'),
        ),
    ]
