# Generated by Django 3.2.13 on 2022-05-31 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0045_auto_20220531_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='billing_physical_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to='events.address', verbose_name='billing address'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
