# Generated by Django 3.2.13 on 2022-06-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_alter_address_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanttype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
