# Generated by Django 3.2.14 on 2022-07-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_applicanttype_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_catered',
            field=models.BooleanField(default=False, help_text='Select if food will be provided at this event'),
        ),
    ]
