# Generated by Django 3.2.14 on 2022-07-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_event_is_catered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='billing_physical_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to='events.address', verbose_name='billing address'),
        ),
    ]
