# Generated by Django 3.2.14 on 2022-07-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_alter_eventapplication_billing_physical_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='billing_email_address',
            field=models.EmailField(max_length=100),
        ),
    ]
