# Generated by Django 3.2.14 on 2022-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_alter_eventapplication_billing_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='participant_email_address',
            field=models.EmailField(default='', max_length=150),
        ),
    ]
