# Generated by Django 3.2.14 on 2022-07-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_eventapplication_participant_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='representing',
            field=models.TextField(default='', help_text='e.g. school, organisation, association, myself', max_length=300),
        ),
    ]
