# Generated by Django 3.2.14 on 2022-07-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_eventapplication_representing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Select if this event is free for all types of participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='accessible_online',
            field=models.BooleanField(default=False, help_text='Select if this event will be attended online'),
        ),
    ]
