# Generated by Django 3.2.14 on 2022-07-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_auto_20220716_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='emergency_contact_first_name',
            field=models.CharField(default='', max_length=50, verbose_name="emergency contact's first name"),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='emergency_contact_last_name',
            field=models.CharField(default='', max_length=50, verbose_name="emergency contact's last name"),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='emergency_contact_phone_number',
            field=models.CharField(default='', max_length=30, verbose_name="emergency contact's phone number"),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='emergency_contact_relationship',
            field=models.CharField(default='', max_length=150, verbose_name='relationship with emergency contact'),
        ),
    ]
