# Generated by Django 3.2.14 on 2022-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_auto_20220716_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='bill_to',
            field=models.CharField(default='', help_text='Who will be paying for you?', max_length=200),
        ),
    ]
