# Generated by Django 3.2.14 on 2022-07-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_alter_eventapplication_bill_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email_address',
            field=models.EmailField(default='', max_length=150),
        ),
    ]
