# Generated by Django 3.2.14 on 2022-07-18 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_event_contact_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='participant_email_address',
        ),
    ]
