# Generated by Django 3.2.14 on 2022-07-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_remove_eventapplication_participant_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='applicant_type',
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='participant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to='events.applicanttype'),
        ),
    ]
