# Generated by Django 3.2.14 on 2022-07-18 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0064_auto_20220718_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantType',
            new_name='ParticipantType',
        ),
        migrations.AddField(
            model_name='event',
            name='facilitators',
            field=models.ManyToManyField(blank=True, related_name='event', to=settings.AUTH_USER_MODEL, verbose_name='Facilitators of this event'),
        ),
    ]
