# Generated by Django 3.2.14 on 2022-07-18 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0065_auto_20220718_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='facilitators',
        ),
        migrations.AddField(
            model_name='session',
            name='facilitators',
            field=models.ManyToManyField(blank=True, related_name='session', to=settings.AUTH_USER_MODEL, verbose_name='Facilitators of this session'),
        ),
    ]
