# Generated by Django 3.2.14 on 2022-07-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0066_auto_20220718_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_approved_applications_prior_bulk_deletion',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_pending_applications_prior_bulk_deletion',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_rejected_applications_prior_bulk_deletion',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_withdrawn_applications_prior_bulk_deletion',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='reason_for_withdrawing',
            field=models.CharField(default='', max_length=300),
        ),
    ]
