# Generated by Django 3.2.14 on 2022-07-21 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0068_deletedeventapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participanttype',
            options={'ordering': ['name'], 'verbose_name_plural': 'participant type'},
        ),
        migrations.AddField(
            model_name='deletedeventapplication',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event_applications', to='events.event'),
        ),
        migrations.AlterField(
            model_name='participanttype',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_types', to='events.event'),
        ),
        migrations.AlterField(
            model_name='session',
            name='facilitators',
            field=models.ManyToManyField(blank=True, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Facilitators of this session'),
        ),
    ]
