# Generated by Django 3.2.14 on 2022-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0069_auto_20220721_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedeventapplication',
            name='other_reason_for_deletion',
            field=models.DateTimeField(blank=True, max_length=300, null=True),
        ),
    ]
