# Generated by Django 3.2.14 on 2022-07-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0070_alter_deletedeventapplication_other_reason_for_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedeventapplication',
            name='date_deleted',
            field=models.DateTimeField(auto_now_add=True, help_text='Date the original event application was deleted'),
        ),
    ]
