# Generated by Django 3.2.14 on 2022-07-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_alter_deletedeventapplication_date_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedeventapplication',
            name='other_reason_for_deletion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
