# Generated by Django 3.2.14 on 2022-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_alter_deletedeventapplication_other_reason_for_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedeventapplication',
            name='deletion_reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Register to attend event'), (2, 'Apply to attend event'), (3, 'Visit event website'), (4, 'This event is invite only'), (5, 'Other')], default=1, help_text='Reason the participant has chosen to withdraw their application.'),
        ),
    ]
