# Generated by Django 3.2.14 on 2022-07-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0074_alter_deletedeventapplication_deletion_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedeventapplication',
            name='deletion_reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prefer not to say'), (2, 'Illness'), (3, 'Not interested'), (4, 'Change of plans'), (5, 'Too expensive / No funding'), (6, 'Inconvient location'), (7, 'Other')], default=1, help_text='Reason the participant has chosen to withdraw their application.'),
        ),
    ]
