# Generated by Django 3.2.14 on 2022-07-30 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0075_alter_deletedeventapplication_deletion_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_approved_applications_prior_bulk_deletion',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_pending_applications_prior_bulk_deletion',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_rejected_applications_prior_bulk_deletion',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_withdrawn_applications_prior_bulk_deletion',
        ),
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
