# Generated by Django 3.2.14 on 2022-07-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0077_rename_staff_event_event_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
    ]
