# Generated by Django 3.2.14 on 2022-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_alter_eventapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
    ]
