# Generated by Django 3.2.15 on 2022-09-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0082_eventapplication_admin_billing_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, help_text='Desired format is YYYY-MM-DD hh:mm:ss, e.g. 2022-06-09 11:30:00 (9th May 2022 at 11.30am)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Desired format is YYYY-MM-DD hh:mm:ss, e.g. 2022-06-09 11:30:00 (9th May 2022 at 11.30am)', null=True),
        ),
    ]
