# Generated by Django 3.2.15 on 2022-09-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0085_event_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventApplicationsCSV',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event_application_csv', serialize=False, to='events.event')),
                ('event_name', models.BooleanField(default=True)),
                ('submitted_datetime', models.BooleanField(default=False)),
                ('updated_datetime', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('participant_type', models.BooleanField(default=False)),
                ('staff_comments', models.BooleanField(default=False)),
                ('participant_first_name', models.BooleanField(default=False)),
                ('participant_last_name', models.BooleanField(default=False)),
                ('representing', models.BooleanField(default=False)),
                ('emergency_contact_first_name', models.BooleanField(default=False)),
                ('emergency_contact_last_name', models.BooleanField(default=False)),
                ('emergency_contact_relationship', models.BooleanField(default=False)),
                ('emergency_contact_phone_number', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('bill_to', models.BooleanField(default=False)),
                ('billing_physical_address', models.BooleanField(default=False)),
                ('billing_email_address', models.BooleanField(default=False)),
                ('admin_billing_comments', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventCSV',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event_csv', serialize=False, to='events.event')),
                ('event_name', models.BooleanField(default=True)),
                ('description', models.BooleanField(default=False)),
                ('published_status', models.BooleanField(default=False)),
                ('show_schedule', models.BooleanField(default=False)),
                ('featured_status', models.BooleanField(default=False)),
                ('registration_type', models.BooleanField(default=False)),
                ('registration_link', models.BooleanField(default=False)),
                ('start_datetime', models.BooleanField(default=False)),
                ('end_datetime', models.BooleanField(default=False)),
                ('accessible_online', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('locations', models.BooleanField(default=False)),
                ('sponsors', models.BooleanField(default=False)),
                ('organisers', models.BooleanField(default=False)),
                ('series', models.BooleanField(default=False)),
                ('is_catered', models.BooleanField(default=False)),
                ('contact_email_address', models.BooleanField(default=False)),
                ('event_staff', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('approved_applications_count', models.BooleanField(default=False)),
                ('pending_applications_count', models.BooleanField(default=False)),
                ('rejected_applications_count', models.BooleanField(default=False)),
                ('withdrawn_applications_count', models.BooleanField(default=False)),
            ],
        ),
    ]
