# Generated by Django 3.2.15 on 2022-09-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0086_eventapplicationscsv_eventcsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplicationscsv',
            name='file_name',
            field=models.CharField(default='events_data', max_length=200),
        ),
        migrations.AddField(
            model_name='eventcsv',
            name='file_name',
            field=models.CharField(default='events_data', max_length=200),
        ),
    ]
