# Generated by Django 3.2.15 on 2022-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0092_auto_20220908_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplicationscsv',
            name='file_name',
            field=models.CharField(default='event_application_data', max_length=200),
        ),
    ]
