# Generated by Django 3.2.15 on 2022-09-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0095_auto_20220910_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_types',
            field=models.ManyToManyField(related_name='events', to='events.Ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('name', 'price')},
        ),
    ]
