# Generated by Django 3.2.15 on 2022-09-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_auto_20220910_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['name'], 'verbose_name_plural': 'ticket type'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_free',
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='participant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to='events.ticket'),
        ),
        migrations.DeleteModel(
            name='ParticipantType',
        ),
    ]
