# Generated by Django 3.2.15 on 2022-09-13 06:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0098_alter_event_ticket_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='terms_and_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
