# Generated by Django 3.2.15 on 2022-09-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0101_alter_registrationform_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='representing',
            field=models.CharField(default='', help_text='e.g. school, organisation, association, myself', max_length=300),
        ),
    ]
