# Generated by Django 3.2.15 on 2022-09-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0102_alter_eventapplication_representing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Ticket'),
        ),
    ]
