# Generated by Django 3.2.15 on 2022-09-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_alter_event_ticket_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='close_datetime',
            field=models.DateTimeField(blank=True, help_text='This is the date and time that participants registerations/applications close for this event. Desired format is YYYY-MM-DD hh:mm:ss, e.g. 2022-06-09 11:30:00 (9th May 2022 at 11.30am)', null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='open_datetime',
            field=models.DateTimeField(blank=True, help_text='This is the date and time that participants can register/apply for this event. Desired format is YYYY-MM-DD hh:mm:ss, e.g. 2022-06-09 11:30:00 (9th May 2022 at 11.30am)', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.DateTimeField(help_text='Desired format is YYYY-MM-DD hh:mm:ss, e.g. 2022-06-09 11:30:00 (9th May 2022 at 11.30am)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.DateTimeField(help_text='Desired format is YYYY-MM-DD hh:mm:ss, e.g. 2022-06-09 11:30:00 (9th May 2022 at 11.30am)'),
        ),
    ]
