# Generated by Django 3.2.15 on 2022-09-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0105_auto_20220921_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text="Only required when the event registration type is 'external'. \n\nThis is a link to an external location that will gather event applications' information e.g. Google Form", null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Register to attend event'), (2, 'Apply to attend event'), (3, 'Visit event website'), (4, 'This event is invite only')], default=1, help_text='Register type events will not require you to approve or reject event reigstration forms.\n\nApply type events require you to approve event applications in order for a participant to be attending this event.'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='close_datetime',
            field=models.DateTimeField(blank=True, help_text='This is the date and time that participants registerations/applications close for this event.\n\nDesired format is YYYY-MM-DD hh:mm:ss, e.g. 2022-06-09 11:30:00 (9th May 2022 at 11.30am)', null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='open_datetime',
            field=models.DateTimeField(blank=True, help_text='This is the date and time that participants can register/apply for this event.\n\nDesired format is YYYY-MM-DD hh:mm:ss, e.g. 2022-06-09 11:30:00 (9th May 2022 at 11.30am)', null=True),
        ),
    ]
