# Generated by Django 3.2.15 on 2022-09-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0107_auto_20220921_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Participant type e.g. teacher, event staff', max_length=200)),
                ('price', models.FloatField(help_text='Cost for participant to attend in NZD')),
            ],
            options={
                'verbose_name_plural': 'ticket type',
                'ordering': ['name'],
                'unique_together': {('name', 'price')},
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, help_text='The ticket types that will be available for event participants to choose from.', related_name='events', to='events.TicketType'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='participant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to='events.tickettype'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
