# Generated by Django 3.2.15 on 2022-09-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0108_auto_20220921_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='representing',
            field=models.CharField(default='', help_text='Who will you be repesenting at this event? e.g. school, organisation, association, myself', max_length=300),
        ),
    ]
