# Generated by Django 3.2.15 on 2022-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0109_alter_eventapplication_representing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedeventapplication',
            name='deletion_reason',
            field=models.PositiveSmallIntegerField(choices=[(3, 'No longer interested')], default=1, help_text='Reason the participant has chosen to withdraw their application.'),
        ),
    ]
