# Generated by Django 3.2.15 on 2022-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0110_alter_deletedeventapplication_deletion_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedeventapplication',
            name='deletion_reason',
            field=models.PositiveSmallIntegerField(choices=[(3, 'No longer interested'), (4, 'Change of plans'), (5, 'No funding'), (6, 'Inconvient location')], default=1, help_text='Reason the participant has chosen to withdraw their application.'),
        ),
    ]
