# Generated by Django 3.2.15 on 2022-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0117_auto_20220928_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Register to attend event (Registrations auto-approved)'), (2, 'Register to attend event (Manual approval required)'), (3, 'Visit external event website'), (4, 'This event is invite only')], default=1, help_text='Register type events will not require you to approve or reject event reigstration forms.\n\nApply type events require you to approve event registrations in order for a participant to be attending this event.'),
        ),
    ]
