# Generated by Django 3.2.15 on 2022-09-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0119_auto_20220928_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
        migrations.RemoveField(
            model_name='eventcsv',
            name='registration_link',
        ),
        migrations.AddField(
            model_name='event',
            name='external_event_registration_link',
            field=models.URLField(blank=True, help_text="Only required when the event registration type is 'external'. \n\nThis is a link to an external location that will gather event registrations' information e.g. Google Form", null=True),
        ),
        migrations.AddField(
            model_name='eventcsv',
            name='external_event_registration_link',
            field=models.BooleanField(default=False),
        ),
    ]
