# Generated by Django 3.2.15 on 2022-10-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0122_alter_eventregistrationscsv_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capcity',
            field=models.IntegerField(default=1, help_text='What is the maximum number of people who can attend this event?', null=True),
        ),
    ]
