# Generated by Django 3.2.15 on 2022-10-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0124_auto_20221007_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=1, help_text='What is the maximum number of people who can attend this event?'),
        ),
    ]
