# Generated by Django 3.2.15 on 2022-10-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0125_alter_event_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedeventregistration',
            name='other_reason_for_deletion',
        ),
        migrations.AddField(
            model_name='deletedeventregistration',
            name='other_reason_for_withdrawl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
