# Generated by Django 3.2.15 on 2022-10-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0126_auto_20221008_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedeventregistration',
            name='other_reason_for_withdrawl',
        ),
        migrations.AddField(
            model_name='deletedeventregistration',
            name='other_reason_for_withdrawing',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
