# Generated by Django 3.2.15 on 2022-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0127_auto_20221008_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='emergency_contact_first_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name="emergency contact's first name"),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='emergency_contact_last_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name="emergency contact's last name"),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='emergency_contact_phone_number',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name="emergency contact's phone number"),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='relationship with emergency contact'),
        ),
    ]
