# Generated by Django 3.2.15 on 2022-10-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0128_auto_20221008_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistrationscsv',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventCSV',
        ),
        migrations.DeleteModel(
            name='EventRegistrationsCSV',
        ),
    ]
