# Generated by Django 3.2.15 on 2022-10-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_user_user_region'),
        ('events', '0129_auto_20221021_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organisers',
            field=models.ManyToManyField(blank=True, related_name='events', to='users.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsored_events', to='users.Entity'),
        ),
    ]
